-- MySQL Script generated by MySQL Workbench
-- 06/09/16 06:51:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema inutricare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inutricare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inutricare` DEFAULT CHARACTER SET utf8 ;
USE `inutricare` ;

-- -----------------------------------------------------
-- Table `inutricare`.`allergies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inutricare`.`allergies` ;

CREATE TABLE IF NOT EXISTS `inutricare`.`allergies` (
  `aid` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`aid`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inutricare`.`caregiver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inutricare`.`caregiver` ;

CREATE TABLE IF NOT EXISTS `inutricare`.`caregiver` (
  `cid` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `firstName` VARCHAR(100) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `DOB` VARCHAR(10) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `site` VARCHAR(200) NOT NULL,
  `preferredname` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cid`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inutricare`.`fooditem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inutricare`.`fooditem` ;

CREATE TABLE IF NOT EXISTS `inutricare`.`fooditem` (
  `fid` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `energy` DOUBLE NULL DEFAULT NULL,
  `totalProt` DOUBLE NULL DEFAULT NULL,
  `totalCarb` DOUBLE NULL DEFAULT NULL,
  `totalFat` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`fid`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inutricare`.`health_conditions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inutricare`.`health_conditions` ;

CREATE TABLE IF NOT EXISTS `inutricare`.`health_conditions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inutricare`.`ingrediants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inutricare`.`ingrediants` ;

CREATE TABLE IF NOT EXISTS `inutricare`.`ingrediants` (
  `iid` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`iid`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inutricare`.`patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inutricare`.`patient` ;

CREATE TABLE IF NOT EXISTS `inutricare`.`patient` (
  `pid` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `firstName` VARCHAR(100) NOT NULL,
  `lastName` VARCHAR(100) NOT NULL,
  `preferredname` VARCHAR(100) NOT NULL,
  `DOB` VARCHAR(10) NOT NULL,
  `street` VARCHAR(200) NULL DEFAULT NULL,
  `postcode` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `state` VARCHAR(45) NULL DEFAULT NULL,
  `phonenumber` VARCHAR(45) NULL DEFAULT NULL,
  `nextkinname` VARCHAR(100) NULL DEFAULT NULL,
  `relationship` VARCHAR(45) NULL DEFAULT NULL,
  `kin_street` VARCHAR(200) NULL DEFAULT NULL,
  `kin_postcode` VARCHAR(45) NULL DEFAULT NULL,
  `kin_city` VARCHAR(45) NULL DEFAULT NULL,
  `kin_state` VARCHAR(45) NULL DEFAULT NULL,
  `kin_phone` VARCHAR(45) NULL DEFAULT NULL,
  `MMSE` VARCHAR(100) NULL DEFAULT NULL,
  `livingstatus` VARCHAR(45) NULL DEFAULT NULL,
  `careplan` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`pid`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inutricare`.`meal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inutricare`.`meal` ;

CREATE TABLE IF NOT EXISTS `inutricare`.`meal` (
  `mid` INT(11) NOT NULL AUTO_INCREMENT,
  `pid` INT(11) NULL DEFAULT NULL,
  `mealtype` VARCHAR(2) NULL DEFAULT NULL,
  `meal_time` DATETIME NULL DEFAULT NULL,
  `prepare_time` TIME NULL DEFAULT NULL,
  `alert_time` TIME NULL DEFAULT NULL,
  `comment` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`mid`),
  INDEX `meal_p_pid_idx` (`pid` ASC),
  CONSTRAINT `meal_p_pid`
    FOREIGN KEY (`pid`)
    REFERENCES `inutricare`.`patient` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inutricare`.`rel_allergies_ingrediants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inutricare`.`rel_allergies_ingrediants` ;

CREATE TABLE IF NOT EXISTS `inutricare`.`rel_allergies_ingrediants` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `iid` INT(11) NULL DEFAULT NULL,
  `aid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `rel_a_i_aid_idx` (`aid` ASC),
  INDEX `rel_a_i_iid_idx` (`iid` ASC),
  CONSTRAINT `rel_a_i_aid`
    FOREIGN KEY (`aid`)
    REFERENCES `inutricare`.`allergies` (`aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rel_a_i_iid`
    FOREIGN KEY (`iid`)
    REFERENCES `inutricare`.`ingrediants` (`iid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inutricare`.`rel_food_consumption`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inutricare`.`rel_food_consumption` ;

CREATE TABLE IF NOT EXISTS `inutricare`.`rel_food_consumption` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fid` INT(11) NULL DEFAULT NULL,
  `mid` INT(11) NULL DEFAULT NULL,
  `calories` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `rel_f_c_fid_idx` (`fid` ASC),
  INDEX `rel_f_c_mid_idx` (`mid` ASC),
  CONSTRAINT `rel_f_c_fid`
    FOREIGN KEY (`fid`)
    REFERENCES `inutricare`.`fooditem` (`fid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rel_f_c_mid`
    FOREIGN KEY (`mid`)
    REFERENCES `inutricare`.`meal` (`mid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inutricare`.`rel_food_ingrediants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inutricare`.`rel_food_ingrediants` ;

CREATE TABLE IF NOT EXISTS `inutricare`.`rel_food_ingrediants` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `fid` INT(11) NULL DEFAULT NULL,
  `iid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fid_idx` (`fid` ASC),
  INDEX `rel_f_i_iid_idx` (`iid` ASC),
  CONSTRAINT `rel_f_i_fid`
    FOREIGN KEY (`fid`)
    REFERENCES `inutricare`.`fooditem` (`fid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rel_f_i_iid`
    FOREIGN KEY (`iid`)
    REFERENCES `inutricare`.`ingrediants` (`iid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inutricare`.`rel_health_ingrediant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inutricare`.`rel_health_ingrediant` ;

CREATE TABLE IF NOT EXISTS `inutricare`.`rel_health_ingrediant` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `hid` INT(11) NULL DEFAULT NULL,
  `iid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `rel_h_i_hid_idx` (`hid` ASC),
  INDEX `rel_h_i_iid_idx` (`iid` ASC),
  CONSTRAINT `rel_h_i_hid`
    FOREIGN KEY (`hid`)
    REFERENCES `inutricare`.`health_conditions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rel_h_i_iid`
    FOREIGN KEY (`iid`)
    REFERENCES `inutricare`.`ingrediants` (`iid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inutricare`.`rel_ingredients_patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inutricare`.`rel_ingredients_patient` ;

CREATE TABLE IF NOT EXISTS `inutricare`.`rel_ingredients_patient` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `iid` INT(11) NULL DEFAULT NULL,
  `pid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inutricare`.`rel_patient_allergies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inutricare`.`rel_patient_allergies` ;

CREATE TABLE IF NOT EXISTS `inutricare`.`rel_patient_allergies` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pid` INT(11) NULL DEFAULT NULL,
  `aid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `rel_p_a_pid_idx` (`pid` ASC),
  INDEX `rel_p_a_aid_idx` (`aid` ASC),
  CONSTRAINT `rel_p_a_aid`
    FOREIGN KEY (`aid`)
    REFERENCES `inutricare`.`allergies` (`aid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rel_p_a_pid`
    FOREIGN KEY (`pid`)
    REFERENCES `inutricare`.`patient` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inutricare`.`rel_patient_caregiver`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inutricare`.`rel_patient_caregiver` ;

CREATE TABLE IF NOT EXISTS `inutricare`.`rel_patient_caregiver` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pid` INT(11) NOT NULL,
  `cid` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `rel_p_c_pid_idx` (`pid` ASC),
  INDEX `rel_p_c_cid_idx` (`cid` ASC),
  CONSTRAINT `rel_p_c_cid`
    FOREIGN KEY (`cid`)
    REFERENCES `inutricare`.`caregiver` (`cid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rel_p_c_pid`
    FOREIGN KEY (`pid`)
    REFERENCES `inutricare`.`patient` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inutricare`.`rel_patient_health`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inutricare`.`rel_patient_health` ;

CREATE TABLE IF NOT EXISTS `inutricare`.`rel_patient_health` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pid` INT(11) NULL DEFAULT NULL,
  `hid` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `rel_p_h_pid_idx` (`pid` ASC),
  INDEX `rel_p_h_hid_idx` (`hid` ASC),
  CONSTRAINT `rel_p_h_hid`
    FOREIGN KEY (`hid`)
    REFERENCES `inutricare`.`health_conditions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `rel_p_h_pid`
    FOREIGN KEY (`pid`)
    REFERENCES `inutricare`.`patient` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inutricare`.`smartmsgs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inutricare`.`smartmsgs` ;

CREATE TABLE IF NOT EXISTS `inutricare`.`smartmsgs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pid` INT(11) NOT NULL,
  `sender` VARCHAR(45) NOT NULL,
  `receiver` VARCHAR(45) NOT NULL,
  `msgContent` VARCHAR(45) NOT NULL,
  `msgTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `smartMsgs_pid_idx` (`pid` ASC),
  CONSTRAINT `smartMsgs_pid`
    FOREIGN KEY (`pid`)
    REFERENCES `inutricare`.`patient` (`pid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
